# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Release Workflow

on:
  workflow_call:
    inputs:
      snapshot:
        required: false
        type: boolean
        default: false

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean ${{ inputs.snapshot && '--snapshot --skip=publish' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}