name: govulncheck

on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: "."
      go-version:
        required: false
        type: string
        default: stable

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
      - name: govulncheck
        working-directory: ${{ inputs.working-directory }}
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...